# Generated by Django 5.2 on 2025-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
