# Generated by Django 5.2 on 2025-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_player_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="score",
            field=models.IntegerField(default=12),
        ),
    ]
