# Generated by Django 5.2 on 2025-05-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_player_is_ready"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="is_ready",
        ),
    ]
